name: Go

on:
  push:
    branches: [ gh-actions ]
  pull_request:
    branches: [ gh-actions ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/maputnik/desktop/

    - name: Get style
      run:  cd src/github.com/maputnik/desktop/ && ls -ll && pwd && wget https://maputnik.github.io/osm-liberty/style.json

    - name: Build
      run: cd src/github.com/maputnik/desktop/ && make

    - name: Test help
      run: /home/runner/go/src/github.com/maputnik/desktop//bin/linux/maputnik --help
   
    - name: Test version
      run: /home/runner/go/src/github.com/maputnik/desktop//bin/linux/maputnik --version
      
    - name: Test watch
      run: /home/runner/go/src/github.com/maputnik/desktop//bin/linux/maputnik --watch --file style.json & sleep 5; kill $!
